---
- hosts: localhost

  tasks:
  - name: Including Secret Environment Items
    include_vars:
      file: secrets.yml
      name: secret
  - debug:
      msg: "{{secret.username}}"

  - name: vcenter login
    uri:
      url: "https://{{secret.hostname}}/rest/com/vmware/cis/session"
      force_basic_auth: yes
      method: POST
      user: "{{secret.username}}"
      password: "{{secret.password}}"
      status_code: 200
      validate_certs: no
    register: login

  - name: Get hosts from vCenter
    uri:
      url: "https://{{secret.hostname}}/rest/vcenter/host"
      force_basic_auth: yes
      validate_certs: no
      headers:
        Cookie: "{{login.set_cookie}}"
