---
- hosts: localhost

  tasks:
  - name: Including Secret Environment Items
    include_vars:
      file: secrets.yml
      name: secret

  - name: vcenter login
    uri:
      url: "https://{{secret.hostname}}/rest/com/vmware/cis/session"
      force_basic_auth: yes
      method: POST
      user: "{{secret.username}}"
      password: "{{secret.password}}"
      status_code: 200
      validate_certs: no
    register: login

  - name: Get hosts from vCenter
    uri:
      url: "https://{{secret.hostname}}/rest/vcenter/host"
      force_basic_auth: yes
      validate_certs: no
      headers:
        Cookie: "{{login.set_cookie}}"
    register: vchosts

  - name: Add NTP settings on esxi hosts
    vmware_host_ntp:
      hostname: "{{secret.hostname}}"
      username: "{{secret.username}}"
      password: "{{secret.password}}"
      esxi_hostname: "{{item.name}}"
      state: present
      ntp_servers:
        - 192.168.1.10
        - 192.168.1.250
      validate_certs: no
    with_items:
      - "{{vchosts.json.value}}"

  - name: Remove old NTP settings on esxi hosts
    vmware_host_ntp:
      hostname: "{{secret.hostname}}"
      username: "{{secret.username}}"
      password: "{{secret.password}}"
      esxi_hostname: "{{item.name}}"
      state: present
      ntp_servers:
        - 192.168.1.245
      validate_certs: no
    with_items:
      - "{{vchosts.json.value}}"